# Generated by Django 4.2.9 on 2024-01-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('images', models.ImageField(null=True, upload_to='images/product')),
                ('price', models.IntegerField()),
                ('short_description', models.CharField(db_index=True, max_length=300, null=True)),
                ('description', models.CharField(db_index=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('is_delete', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=130)),
                ('url_title', models.CharField(db_index=True, max_length=130)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Products Category',
                'verbose_name_plural': 'Product  Category',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_caption', models.CharField(db_index=True, max_length=120)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product_module.product')),
            ],
            options={
                'verbose_name': 'Product  Tag',
                'verbose_name_plural': 'Product  Tag',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productbrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='product_module.productcategory'),
        ),
    ]
