# Generated by Django 5.0.1 on 2024-02-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_productcategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
    ]
