# Generated by Django 4.2.9 on 2024-01-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=130)),
                ('site_url', models.CharField(blank=True, max_length=130)),
                ('adress', models.CharField(blank=True, max_length=130)),
                ('phone_sweden', models.CharField(blank=True, max_length=130)),
                ('phone_iran', models.CharField(blank=True, max_length=130)),
                ('fax', models.CharField(blank=True, max_length=130)),
                ('email', models.CharField(blank=True, max_length=130)),
                ('copy_right', models.TextField(blank=True, max_length=130)),
                ('about_us_text', models.TextField(blank=True, max_length=130)),
                ('site_logo', models.ImageField(blank=True, max_length=130, upload_to='')),
                ('is_main_setting', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_name', models.CharField(max_length=130)),
                ('url', models.URLField(max_length=130)),
                ('url_title', models.CharField(max_length=130)),
                ('description', models.TextField(max_length=130)),
                ('image', models.ImageField(upload_to='images/sliders')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slider',
            },
        ),
    ]
