# Generated by Django 5.0.1 on 2024-02-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings_module', '0002_sitesettings_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(upload_to='images/banners')),
                ('is_active', models.BooleanField()),
                ('position', models.CharField(choices=[('product_list', 'Product List'), ('product_detail', 'Product Detail'), ('about_us', 'About Us')], max_length=200)),
            ],
        ),
    ]
