# Generated by Django 4.2.9 on 2024-01-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('Email', models.EmailField(max_length=130)),
                ('Name_and_Surname', models.CharField(max_length=130)),
                ('Message', models.TextField(max_length=300)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('is_read_by_admin', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
