# Generated by Django 5.0.1 on 2024-02-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
